### ISSUE TITLE
Unix Sockets supported?

### ISSUE THREAD

**Issue by Dunuin** [cloudtemple/zabbix_templates#2]
Is it possible to use unix sockets?

I tried to use "unix:///tmp/redis.sock" as "{$REDIS.CONN.URI}" because my Redis uses the unix socket "/tmp/redis.sock" instead of TCP/port but that isn't working.

I'm running Redis and Zabbix on FreeBSD 11.3.

**Comment by cloudtemple** [comment]
Yes, by now.
